version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "gameoflife-backend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-seot9dkgdyy8"
s3_prefix = "gameoflife-backend"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
